modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="netherplus"
version="1.0.0"
displayName="Nether+"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Remag, MCreator"

[[dependencies.netherplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.netherplus]]
    modId="geckolib"
    mandatory=false
    ordering="NONE"
    side="BOTH"

